// Generated by CoffeeScript 1.8.0
(function() {
  var backbone;

  backbone = require('backbone4000');

  exports.lego = backbone.Model.extend4000({
    requires: 'logger',
    init: function(callback) {
      return true;
    }
  });

}).call(this);
